name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - run: uvx ruff@0.16.9 check .
      - run: uvx ruff@0.16.9 format --check .

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.14"
      - run: uv venv && uv pip install -r requirements_test.txt
      - run: uv run --no-project pytest
